[strings.blockly.categories]
LISTS = "List"
TEXT = "Text"
MATH = "Math"
LOGIC = "Logic"
DICTIONARY = "Dictionary"
DEFINITION = "Definitions"
DISCORD = "Discord"
MISCELLANEOUS = "Miscellaneous"
WORKFLOW = "Workflow"
DISCORDMODELS = "Models"
TIME = "Time"


[strings.blockly.messages]
ADD_COMMENT = "Add comment"
CLEAN_UP = "Arrange blocks"
COLLAPSE_ALL = "Collapse blocks"
COLLAPSE_BLOCK = "Collapse block"
DELETE_ALL_BLOCKS = "Delete %1 blocks?"
DELETE_BLOCK = "Delete block"
DELETE_VARIABLE = "Delete definition"
DELETE_VARIABLE_CONFIRMATION = "Delete %1 uses of the '%2' definition?"
DELETE_X_BLOCKS = "Delete %1 blocks"
DIALOG_CANCEL = "Cancel"
DIALOG_OK = "OK"
DISABLE_BLOCK = "Disable block"
DUPLICATE_BLOCK = "Duplicate block"
DUPLICATE_COMMENT = "Duplicate comment"
ENABLE_BLOCK = "Enable block"
EXPAND_ALL = "Expand blocks"
EXPAND_BLOCK = "Expand block"
EXTERNAL_INPUTS = "External inputs"
HELP = "Help"
INLINE_INPUTS = "Inline inputs"
NEW_VARIABLE = "Create..."
NEW_VARIABLE_TITLE = "Name:"
REDO = "Redo"
REMOVE_COMMENT = "Delete comment"
RENAME_VARIABLE = "Rename..."
RENAME_VARIABLE_TITLE = "Rename '%1':"
UNDO = "Undo"
UNNAMED_KEY = "unnamed"
EMPTY_BACKPACK = "Empty backpack"
REMOVE_FROM_BACKPACK = "Remove from backpack"
COPY_TO_BACKPACK = "Copy to backpack"
COPY_ALL_TO_BACKPACK = "Copy all blocks to backpack"
PASTE_ALL_FROM_BACKPACK = "Paste all blocks from backpack"
VARIABLES_DEFAULT_NAME = "name"
VARIABLE_ALREADY_EXISTS = "Definition with '%1' name already exists."
VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE = "Definition with '%1' name already exists."
WORKSPACE_ARIA_LABEL = "Blockly Workspace"
MUTATOR_LIST_CONTAINER = "list"
MUTATOR_LIST_ITEM = "item"
MUTATOR_DICTIONARY_CONTAINER = "dictionary"
MUTATOR_DICTIONARY_ITEM = "pair"
CONTEXT_COPY_WEBHOOK_URL = "Copy Webhook URL"
CONTEXT_COPY_WORKFLOW_ID = "Copy Workflow ID"
CONTEXT_VIEW_LIVE_LOGS = "View live logs"
CONTEXT_RENAME_FUNCTION = "Rename function"
CONTEXT_GO_FUNCTION = "Go to function"
CONTEXT_EXPORT_BLOCKS_ALL = "Export blocks (All)"
CONTEXT_EXPORT_BLOCKS_MARKED = "Export blocks (Only marked)"
CONTEXT_MARK_FOR_EXPORT = "Mark block for export"
CONTEXT_CLEAR_MARK = "Clear all marks"
TOOLBOX_LABEL_MESSAGES = "Messages"
TOOLBOX_LABEL_ENTITIES = "Entities"
TOOLBOX_LABEL_CHANNELS = "Channels"
TOOLBOX_LABEL_MEMBERS = "Members"
TOOLBOX_LABEL_SERVER = "Server"
TOOLBOX_LABEL_ROLES = "Roles"
TOOLBOX_LABEL_INTERACTIONS = "Interactions"
TOOLBOX_LABEL_WEBHOOKS = "Webhooks"
TOOLBOX_LABEL_VARIABLES = "Variables"
TOOLBOX_LABEL_FUNCTIONS = "Functions"
TOOLBOX_LABEL_WEB = "Web"
TOOLBOX_LABEL_LOG = "Log"
TOOLBOX_BUTTON_CREATE_FUNCTION_VARIABLE = "Create function"
TOOLBOX_BUTTON_CREATE_GLOBAL_VARIABLE = "Create Global variable"
TOOLBOX_BUTTON_CREATE_LOCAL_VARIABLE = "Create Local variable"
WARNING_NON_INTERACTION = "This block can only work under an interaction listener."
WARNING_CHAIN_MODAL = "You can't display a modal after modal submit."
WARNING_MULTIPLE_INTERACTION_REPLY = "You only need to respond to interactions once. You cannot respond more than one time."
WARNING_NO_INTERACTION_REPLY = "Interaction events require to be responded."
WARNING_CANNOT_WAIT_MODAL = "You can't send a wait reply as a response to a dialog."
WARNING_DUPLICATE_FUNCTION = "A function can't be defined more than once."
WARNING_DUPLICATE_EVENTS = "An event can't be defined more than once."
WARNING_INVALID_SETTER_GETTER = "This parameter block can only be used within the block it belongs to."


[strings.blockly.values]
EVENT_MESSAGE_SEND = "Message Send"
EVENT_MESSAGE_DELETE = "Message Delete"
EVENT_MESSAGE_DELETE_BULK = "Message Delete Bulk"
EVENT_MESSAGE_EDIT = "Message Edit"
EVENT_REACTION_ADD = "Reaction Add"
EVENT_REACTION_REMOVE = "Reaction Remove"
EVENT_REACTION_REMOVE_ALL = "Reaction Clear"
EVENT_REACTION_REMOVE_EMOJI = "Reaction Clear Emoji"
EVENT_CHANNEL_CREATE = "Channel Create"
EVENT_CHANNEL_DELETE = "Channel Delete"
EVENT_CHANNEL_UPDATE = "Channel Update"
EVENT_CHANNEL_PINS_UPDATE = "Channel Pins Update"
EVENT_MEMBER_JOIN = "Member Join"
EVENT_MEMBER_REMOVE = "Member Remove"
EVENT_MEMBER_BAN = "Member Ban"
EVENT_MEMBER_UNBAN = "Member Unban"
EVENT_SERVER_UPDATE = "Server Update"
EVENT_VOICE_STATE_UPDATE = "Voice State Update"
INCLUDES_ALL = "all"
INCLUDES_ANY = "any"
MAX = "max"
MIN = "min"
MAX_LIST = "max list"
MIN_LIST = "min list"
TRUE = "true"
FALSE = "false"
OR = "or"
AND = "and"
NOR = "nor"
NAND = "nand"
XOR = "xor"
XNOR = "xnor"
PLACEHOLDER_TEXT = "Text"
PLACEHOLDER_MULTILINE_TEXT = "Multi-line text"
TITLE = "title"
DESCRIPTION = "description"
URL = "url"
TIMESTAMP = "timestamp"
IMAGE = "image"
THUMBNAIL = "thumbnail"
FIELDS = "fields"
FOOTER = "footer"
AUTHOR = "author"
COLOR = "color"
NAME = "name"
VALUE = "value"
INLINE = "inline"
ID = "id"
TYPE = "type"
ALLOW = "allow"
DENY = "deny"
TEXT = "text"
ICON_URL = "icon url"
ROLES = "roles"
USERS = "users"
EVERYONE = "everyone"
REPLIED_USER = "replied user"
USER = "user"
REASON = "reason"
ICON = "icon"
SPLASH = "splash"
OWNER_ID = "owner id"
BOOST_LEVEL = "boost level"
CHANNELS = "channels"
FEATURES = "features"
NSFW_LEVEL = "nsfw level"
POSITION = "position"
TOPIC = "topic"
PARENT_ID = "parent id"
PERMISSIONS = "permissions"
LAST_MESSAGE_ID = "last message id"
LAST_PIN_TIMESTAMP = "last pin timestamp"
BITRATE = "bitrate"
COOLDOWN = "cooldown"
USER_LIMIT = "user limit"
HOIST = "hoist"
MANAGED = "managed"
MENTIONABLE = "mentionable"
BOOST_ROLE = "boost role"
NSFW = "nsfw"
CHANNEL = "channel"
MEMBER = "member"
CONTENT = "content"
EDITED_TIMESTAMP = "edited timestamp"
EMBEDS = "embeds"
REACTIONS = "reactions"
MENTION_EVERYONE = "mention everyone"
MENTION_ROLES = "mention roles"
MENTIONS = "mentions"
PINNED = "pinned"
AVATAR = "avatar"
NICKNAME = "nickname"
JOINED_AT = "joined at"
BOOSTING_SINCE = "boosting since"
DEAF = "deaf"
MUTE = "mute"
PENDING = "pending"
USERNAME = "username"
DEFAULT_AVATAR = "default avatar"
BOT = "bot"
SYSTEM = "system"
FLAGS = "flags"
IS_ANIMATED = "is animated"
IS_UNICODE = "is unicode"
DISCRIMINATOR = "discriminator"
LOCALE = "locale"
SERVER_LOCALE = "server locale"
STYLE = "style"
LABEL = "label"
DISABLED = "disabled"
CUSTOM_ID = "custom id"
COUNT = "count"
ME = "me"
MESSAGE = "message"
DATA = "data"
IDS = "ids"
MESSAGES = "messages"
CHANNEL_ID = "channel id"
MESSAGE_ID = "message id"
USER_ID = "user id"
EMOJI = "emoji"
INTERACTION = "interaction"
TIMEOUT = "timeout"
MIN_LENGTH = "min length"
MAX_LENGTH = "max length"
REQUIRED = "required"
PLACEHOLDER = "placeholder"
DEFAULT = "default"
OPTIONS = "options"
MIN_VALUES = "min values"
MAX_VALUES = "max values"
CONTEXT_USER = "User"
CONTEXT_MESSAGE = "Message"
PLACEHOLDER_SLASH_NAME = "slash-name"
PLACEHOLDER_CONTEXT_NAME = "Option Name"
PLACEHOLDER_VALUE = "value"
TRANSLATION_NAME = "name"
TRANSLATION_DESCRIPTION = "description"


[strings.blockly.fields]
DISCORD_CHANNEL = "channel"
DISCORD_MESSAGE = "message"
DISCORD_MESSAGES = "messages"
DISCORD_CONTENT = "content"
DISCORD_EMBED = "embed"
DISCORD_REPLY = "reply"
DISCORD_MENTIONS = "mentions"
DISCORD_EMOJI = "emoji"
DISCORD_USER = "user"
DISCORD_LIMIT = "limit"
DISCORD_AFTER = "after"
DISCORD_BEFORE = "before"
DISCORD_AROUND = "around"
DISCORD_OLDEST_FIRST = "oldest first"
DISCORD_NAME = "name"
DISCORD_TYPE = "type"
DISCORD_POSITION = "position"
DISCORD_TOPIC = "topic"
DISCORD_NSFW = "nsfw"
DISCORD_COOLDOWN = "cooldown"
DISCORD_BITRATE = "bitrate"
DISCORD_USER_LIMIT = "user limit"
DISCORD_PERMISSIONS = "permissions"
DISCORD_CATEGORY = "category"
DISCORD_REASON = "reason"
DISCORD_MEMBER = "member"
DISCORD_DELETE_DAYS = "delete days"
DISCORD_ROLES = "roles"
DISCORD_COMPUTE_PRUNE_COUNT = "compute prune count"
DISCORD_COLOR = "color"
DISCORD_HOIST = "hoist"
DISCORD_MENTIONABLE = "mentionable"
DISCORD_DAYS = "days"
DISCORD_EPHEMERAL = "ephemeral"
DISCORD_COMPONENTS = "components"
DISCORD_SHOW_WAIT = "show wait"
DISCORD_WEBHOOK_ID = "webhook id"
DISCORD_WEBHOOK_TOKEN = "webhook token"
DISCORD_USERNAME = "username"
DISCORD_AVATAR_URL = "avatar url"
DISCORD_CUSTOM_ID = "custom id"
DISCORD_UPDATE = "update"
DISCORD_TITLE = "title"
DISCORD_NICK = "nick"
DISCORD_DEAF = "deaf"
DISCORD_MUTE = "mute"
DISCORD_VOICE_CHANNEL = "voice channel"
DISCORD_TIMEOUT = "timeout"
DICTIONARY_KEY = "key"
DICTIONARY_VALUE = "value"
DICTIONARY_DICTIONARY = "dictionary"
DICTIONARY_DEFAULT = "default"
LISTS_LIST = "list"
LISTS_ITEMS = "items"
LISTS_ITEM = "item"
LISTS_INDEX = "index"
LISTS_REVERSE = "reverse"
LISTS_STOP = "stop"
LISTS_START = "start"
LISTS_STEP = "step"
LOGIC_VALUE = "value"
LOGIC_THEN = "then"
LOGIC_OTHERWISE = "otherwise"
TEXT_TEXT = "text"
TEXT_PIECES = "pieces"
TEXT_PIECE = "piece"
TEXT_SEPERATOR = "seperator"
TEXT_INDEX = "index"
TEXT_OLD = "old"
TEXT_NEW = "new"
TEXT_COUNT = "count"
TEXT_CHARS = "chars"
TEXT_MAXSPLIT = "max split"
TEXT_KEEP_ENDS = "keep ends"
TEXT_LIST = "list"
TEXT_STOP = "stop"
TEXT_START = "start"
TEXT_STEP = "step"
MATH_LIST = "list"
MATH_START = "start"
DISCORDM_TITLE = "title"
DISCORDM_DESCRIPTION = "description"
DISCORDM_URL = "url"
DISCORDM_TIMESTAMP = "timestamp"
DISCORDM_IMAGE = "image"
DISCORDM_THUMBNAIL = "thumbnail"
DISCORDM_FIELDS = "fields"
DISCORDM_FOOTER = "footer"
DISCORDM_AUTHOR = "author"
DISCORDM_COLOR = "color"
DISCORDM_NAME = "name"
DISCORDM_VALUE = "value"
DISCORDM_INLINE = "inline"
DISCORDM_ID = "id"
DISCORDM_TYPE = "type"
DISCORDM_ALLOW = "allow"
DISCORDM_DENY = "deny"
DISCORDM_TEXT = "text"
DISCORDM_ICON_URL = "icon url"
DISCORDM_ROLES = "roles"
DISCORDM_USERS = "users"
DISCORDM_EVERYONE = "everyone"
DISCORDM_REPLIED_USER = "replied user"
DISCORDM_STYLE = "style"
DISCORDM_LABEL = "label"
DISCORDM_EMOJI = "emoji"
DISCORDM_DISABLED = "disabled"
DISCORDM_CUSTOM_ID = "custom id"
DISCORDM_MIN_LENGTH = "min length"
DISCORDM_MAX_LENGTH = "max length"
DISCORDM_REQUIRED = "required"
DISCORDM_PLACEHOLDER = "placeholder"
DISCORDM_DEFAULT = "default"
DISCORDM_OPTIONS = "options"
DISCORDM_MIN_VALUES = "min values"
DISCORDM_MAX_VALUES = "max values"
MISCELLANEOUS_URL = "url"
MISCELLANEOUS_METHOD = "method"
MISCELLANEOUS_HEADERS = "headers"
MISCELLANEOUS_DATA = "data"
MISCELLANEOUS_PARAMS = "params"
WORKFLOW_PARAMS = "params"
WORKFLOW_DO = "do"
WORKFLOW_NAME = "name"
WORKFLOW_DESCRIPTION = "description"
WORKFLOW_REQUIRED = "required"
TIME_YEAR = "year"
TIME_MONTH = "month"
TIME_DAY = "day"
TIME_HOUR = "hour"
TIME_MINUTE = "minute"
TIME_SECOND = "second"
TIME_TIMEZONE = "timezone"
TIME_MINUTES = "minutes"
TIME_HOURS = "hours"


[strings.blockly.blocks]
DICTIONARY_CREATE_EMPTY = "create empty dictionary"
DICTIONARY_CREATE = "create dictionary"
DICTIONARY_CREATE_FROM_LIST = "create from list"
DICTIONARY_GET = "get"
DICTIONARY_SET = "set"
DICTIONARY_DELETE = "delete"
DICTIONARY_MERGE = "merge"
DICTIONARY_POP = "pop"
DICTIONARY_UPDATE = "update"
DICTIONARY_CLEAR = "clear"
DICTIONARY_COUNT = "count"
DICTIONARY_LIST_KEYS = "list keys"
DICTIONARY_LIST_VALUES = "list values"
DICTIONARY_LIST_ITEMS = "list items"
DICTIONARY_IS_DICTIONARY = "is dictionary"
DICTIONARY_IS_KEY_EXISTS = "is key exists"
DICTIONARY_IS_VALUE_EXISTS = "is value exists"
LISTS_CREATE_EMPTY = "create empty list"
LISTS_CREATE = "create list"
LISTS_COUNT = "count"
LISTS_APPEND = "append"
LISTS_INCLUDES = "includes"
LISTS_CLEAR = "clear"
LISTS_EXTEND = "extend"
LISTS_SORT = "sort"
LISTS_INSERT = "insert"
LISTS_COPY = "copy"
LISTS_REMOVE = "remove"
LISTS_POP = "pop"
LISTS_REVERSE = "reverse"
LISTS_COUNT_ITEM = "count item"
LISTS_MERGE = "merge"
LISTS_FLATTEN = "flatten"
LISTS_GET = "get"
LISTS_RANDOM = "random"
LISTS_INDEX = "index"
LISTS_RANGE = "range"
WORKFLOW_EVENT_LISTENER = "listener"
WORKFLOW_IF = "if"
WORKFLOW_IF_ELSE = "else"
WORKFLOW_LOOP_FOR_EACH = "for each item in list"
WORKFLOW_DUMMY = "do"
LOGIC_STOP = "stop workflow"
LOGIC_NONE = "none"
LOGIC_BOOL = "bool"
LOGIC_IS_NONE = "is none"
LOGIC_IF_THEN_ELSE = "if"
LOGIC_LOGICAL_NOT = "not"
LOGIC_ASSERT = "assert"
LOGIC_NOT_ASSERT = "not assert"
LOGIC_BITWISE_NOT = "bitwise not"
LOGIC_BITWISE_AND = "bitwise and"
LOGIC_BITWISE_OR = "bitwise or"
LOGIC_BITWISE_XOR = "bitwise xor"
TEXT_INCLUDES = "includes"
TEXT_CREATE = "text"
TEXT_JOIN = "join"
TEXT_JOIN_LIST = "join list"
TEXT_COUNT = "count"
TEXT_GET = "get"
TEXT_COUNT_PIECE = "count piece"
TEXT_IS_EMPTY = "is empty"
TEXT_STRIP = "strip"
TEXT_UPPERCASE = "uppercase"
TEXT_LOWERCASE = "lowercase"
TEXT_SPLIT = "split"
TEXT_SPLIT_LINES = "split lines"
TEXT_SPLIT_CHARS = "split chars"
TEXT_TITLECASE = "titlecase"
TEXT_STARTS_WITH = "starts with"
TEXT_ENDS_WITH = "ends with"
TEXT_IS_NUMERIC = "is numeric"
TEXT_IS_ALPHA = "is alphabetic"
TEXT_IS_TEXT = "is text"
TEXT_REPLACE = "replace"
TEXT_SLICE = "slice"
TEXT_REPEAT = "repeat"
DISCORD_MESSAGE_PIN = "message pin"
DISCORD_MESSAGE_UNPIN = "message unpin"
DISCORD_MESSAGE_DELETE = "message delete"
DISCORD_MESSAGE_BULK_DELETE = "message bulk delete"
DISCORD_MESSAGE_SEND = "message send"
DISCORD_MESSAGE_DM = "message dm"
DISCORD_MESSAGE_EDIT = "message edit"
DISCORD_MESSAGE_ADD_REACTION = "message add reaction"
DISCORD_MESSAGE_REMOVE_REACTION = "message remove reaction"
DISCORD_MESSAGE_GET_REACTION = "message get reaction"
DISCORD_CHANNEL = "channel"
DISCORD_CHANNELS = "channels"
DISCORD_CHANNEL_HISTORY = "channel history"
DISCORD_CHANNEL_CREATE = "channel create"
DISCORD_CHANNEL_EDIT = "channel edit"
DISCORD_CHANNEL_DELETE = "channel delete"
DISCORD_MEMBER = "member"
DISCORD_MEMBER_ME = "relay itself"
DISCORD_MEMBER_BAN = "member ban"
DISCORD_MEMBER_UNBAN = "member unban"
DISCORD_MEMBER_KICK = "member kick"
DISCORD_MEMBER_EDIT = "member edit"
DISCORD_SERVER = "server"
DISCORD_SERVER_GET_BAN = "server get ban"
DISCORD_SERVER_GET_PRUNE = "server get prune"
DISCORD_SERVER_BEGIN_PRUNE = "server begin prune"
DISCORD_ROLE = "role"
DISCORD_ROLES = "roles"
DISCORD_ROLE_CREATE = "role create"
DISCORD_ROLE_DELETE = "role delete"
DISCORD_INTERACTION_REPLY_WAIT = "interaction reply wait"
DISCORD_INTERACTION_REPLY_MESSAGE = "interaction reply message"
DISCORD_INTERACTION_REPLY_MODAL = "interaction reply modal"
DISCORD_INTERACTION_EDIT_MESSAGE = "interaction edit message"
DISCORD_INTERACTION_GET_MESSAGE = "interaction get message"
DISCORD_INTERACTION_DELETE_MESSAGE = "interaction delete message"
DISCORD_INTERACTION_CREATE_FOLLOWUP = "interaction create followup"
DISCORD_INTERACTION_EDIT_FOLLOWUP = "interaction edit followup"
DISCORD_INTERACTION_GET_FOLLOWUP = "interaction get followup"
DISCORD_INTERACTION_DELETE_FOLLOWUP = "interaction delete followup"
DISCORD_WEBHOOK_CREATE_MESSAGE = "webhook create message"
DISCORD_WEBHOOK_EDIT_MESSAGE = "webhook edit message"
DISCORD_WEBHOOK_GET_MESSAGE = "webhook get message"
DISCORD_WEBHOOK_DELETE_MESSAGE = "webhook delete message"
MATH_CREATE_INTEGER = "integer"
MATH_CREATE_FLOAT = "float"
MATH_SUM_LIST = "sum list"
MATH_FLOOR = "floor"
MATH_CEILING = "ceiling"
MATH_SQRT = "sqrt"
MATH_ABS = "abs"
MATH_RANDOM = "random"
DISCORDM_EMBED = "embed"
DISCORDM_OVERWRITES = "overwrites"
DISCORDM_EMBEDAUTHOR = "embed author"
DISCORDM_EMBEDFIELD = "embed field"
DISCORDM_EMBEDFOOTER = "embed footer"
DISCORDM_MENTIONS = "mentions"
DISCORDM_BUTTON = "button"
DISCORDM_TEXTINPUT = "text input"
DISCORDM_SELECT = "select menu"
DISCORDM_SELECTOPTION = "select menu option"
DISCORDM_MODEL_BAN = "ban"
DISCORDM_MODEL_OVERWRITES = "overwrites"
DISCORDM_MODEL_MENTIONS = "mentions"
DISCORDM_MODEL_EMOJI = "emoji"
DISCORDM_MODEL_EMBEDFOOTER = "embed footer"
DISCORDM_MODEL_EMBEDFIELD = "embed field"
DISCORDM_MODEL_EMBEDAUTHOR = "embed author"
DISCORDM_MODEL_EMBED = "embed"
DISCORDM_MODEL_USER = "user"
DISCORDM_MODEL_MEMBER = "member"
DISCORDM_MODEL_ROLE = "role"
DISCORDM_MODEL_MESSAGE = "message"
DISCORDM_MODEL_CHANNEL = "channel"
DISCORDM_MODEL_SERVER = "server"
DISCORDM_MODEL_INTERACTION = "interaction"
DISCORDM_MODEL_BUTTON = "button"
DISCORDM_MODEL_TEXTINPUT = "text input"
DISCORDM_MODEL_REACTION = "reaction"
DISCORDM_MODEL_SELECT = "select menu"
DISCORDM_MODEL_SELECTOPTION = "select menu option"
DISCORDM_COMPONENT_ROW = "component row"
VARIABLE_SET = "set"
VARIABLE_GET = "get"
FUNCTION_CREATE = "function"
FUNCTION_RETURN = "return"
FUNCTION_CALL = "call"
FUNCTION_VALUE = "argument"
WORKFLOW_EVENT_ID = "listener id"
WORKFLOW_SLASH_LISTENER = "slash command listener"
WORKFLOW_COMPONENT_LISTENER = "message component listener"
WORKFLOW_CONTEXT_LISTENER = "context menu listener"
WORKFLOW_MODAL_LISTENER = "modal response listener"
WORKFLOW_WEBHOOK_LISTENER = "webhook listener"
WORKFLOW_SLASH_PARAMETER_TEXT = "text parameter"
WORKFLOW_COMMAND_TRANSLATION = "command locale"
MISCELLANEOUS_HTTP_REQUEST = "http request"
MISCELLANEOUS_HTTP_STATUS = "http status"
MISCELLANEOUS_HTTP_HEADERS = "http headers"
MISCELLANEOUS_HTTP_CONTENT = "http content"
MISCELLANEOUS_DISPLAY_LOG = "display log"
TIME_NOW = "now"
TIME_NOW_TIMEZONE = "now timezone"
TIME_NOW_SECONDS = "now seconds"
TIME_YEAR = "year"
TIME_MONTH = "month"
TIME_DAY = "day"
TIME_HOUR = "hour"
TIME_MINUTE = "minute"
TIME_SECOND = "second"
TIME_CREATE_DATETIME = "create datetime"
TIME_TIMEZONE = "timezone"


[strings.blockly.tooltips]
LISTS_CREATE = "Creates a new list with given values."
DICTIONARY_CREATE = "Creates a new dictionary with given pairs. Dictionaries are objects that holds a value along with a key. Key can be used to get the value."
WORKFLOW_EVENT_LISTENER = "Listen for a specific action and do something when this event happens."
WORKFLOW_SLASH_LISTENER = "Creates a new slash command only for this server. Slash commands can also have parameters."
WORKFLOW_CONTEXT_LISTENER = "Add an option that will show when you right-click on a user or message (context menu) and do something when that option is clicked."
WORKFLOW_COMPONENT_LISTENER = "If any component in the slash command with the name you specify gets an interaction, do something."
WORKFLOW_MODAL_LISTENER = "Do something when a dialog with the specified ID is sent."
WORKFLOW_WEBHOOK_LISTENER = "Creates a new webhook. When this webhook's URL receives an HTTP POST request, do something."
WORKFLOW_CUSTOM_ACTION = "Execute a custom action by typing its name and providing a dictionary of parameters."
WORKFLOW_IF = "Do action when specific condition has met."
WORKFLOW_IF_ELSE = "Do action when specific condition has met. If condition is negative, only runs blocks in 'else' part."
WORKFLOW_LOOP_FOR_EACH = "Do action for each item in list."
WORKFLOW_DUMMY = "A dummy block that can be used for ignore the return value of a block."
WORKFLOW_EVENT_ID = "Returns the ID of the listener block this block is in."
WORKFLOW_COMMAND_TRANSLATION = "Adds a translation for the application command. To add translation, add this block under to \"parameters\" of the command listener. In this way, users will see the names and descriptions of the commands in their Discord language."
FUNCTION_VALUE = "Gets the argument which passed when calling the function."
FUNCTION_RETURN = "Stop the function here and return a value for call block."
FUNCTION_CREATE = "Defines a function. Functions are useful to decrease the repeating code. They can be executed with \"call\" block in anywhere and anytime."
FUNCTION_CALL = "Executes the function and gets the return value which returned in function definition."
LOGIC_STOP = "Stops the workflow right here. Next blocks won't be executed."
DISCORDM_COMPONENT_ROW = "Adds a new row for components."