name: Publish Mkdocs
on:
  push:
    paths:
      - 'docs/**'
      - 'relay/actions/**'
      - '.github/**'
      - 'mkdocs.yml'
      - 'relay/models.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools
        pip install -U wheel
        pip install livereload
        pip install -r docs/requirements.txt
        pip install -r requirements.txt
    - name: Mkdocs GitHub publish
      run: |
        mkdocs gh-deploy --clean -v --force --remote-branch gh-pages
      env:
        MKDOCS_ENABLED: 1
